version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpass
      POSTGRES_DB: walletdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U walletuser -d walletdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  wallet-service:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=walletuser
      - POSTGRES_PASSWORD=walletpass
      - POSTGRES_DB=walletdb
      - SERVER_PORT=8080
      - MAX_DB_CONNECTIONS=50
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
  